### ISSUE TITLE
Looks very interesting

### ISSUE THREAD

**Issue by alexlib** [yongleex/SBCC#1]
Hi, @yongleex - this looks very interesting work. Could you please share some more reading material about the idea? Thanks @alexlib

**Comment by yongleex** [comment]
Hi, @alexlib Thanks for your interest. At present, our work is under review for publication in a journal. In light of this condition, I will ask the editor for permission. Once possible, I will provide the arxiv link for you. Please give me some time. Besides, our other interesting work [DiffeomorphicPIV ](https://github.com/yongleex/DiffeomorphicPIV) has a detailed arxiv preprint.  I hope it helps.

**Comment by alexlib** [comment]
I could wait for a reviewed one, no problem. I have read the other work, thanks. It is also interesting. As well as an NN work. Many new ideas and we at openpiv need to think what is the next useful extension for PIV users.

**Comment by yongleex** [comment]
Hi, @alexlib. I cannot deposit it in ArXiv according to the editor's reply. I'll share it to you via email when possible, it might take several months for the review processing.

Your OpenPIV is a great work, and I like it as an open-source PIV package. We also have several works on PIV with public-available codes ([PIV-DCNN](https://github.com/yongleex/PIV-DCNN), [MVFC](https://github.com/yongleex/MVFC), [DiffeomorphicPIV](https://github.com/yongleex/DiffeomorphicPIV), [SBCC](https://github.com/yongleex/SBCC)). If possible, we are glad to contribute them to the OpenPIV package.  

As a PIV researcher, I expect the accurate and robust algorithms which towards to high DVR and DSR PIV measurement.  Deep learning based methods are emerging, but the uncertainty analysis is the deficience of those methods.

**Comment by alexlib** [comment]
@yongleex no problem and no hurry. 

regarding your suggestion to include your work in OpenPIV - it's a great idea. Let's move this discussion to the openpiv forum - we'll need some support from the community and see how to make it transparent for the users. Our major theme is simplicity. New users are often quickly confused with the multiple options and move away, usually to GUI based, simple software packages.

**Comment by yongleex** [comment]
Hi, @alexlib. As the paper has been rejected due to the experimental design problem, I have uploaded an arxiv version of this work([https://arxiv.org/abs/2112.05303](https://arxiv.org/abs/2112.05303)). I will further update it with new experiments when they are finished. I hope it helps.
[2112.05303.pdf](https://github.com/yongleex/SBCC/files/7716984/2112.05303.pdf)
.
